/basic_trajectory:
  ros__parameters:
    names:
      left_wheel_motor: left_wheel_motor
      pan_motor: pan_motor
      right_wheel_motor: right_wheel_motor
      tilt_motor: tilt_motor
    predict:
      max_buffer_len: 300
    range_lut:
      ratio: 0.8382
      step: 0.5
      values:
      - 0.0
      - 0.5
    solver:
      max_time: 5.0
      min_pose_samples: 10
      run_period: 0.25
      time_step: 0.2
    topic:
      motor_template: motor/{}/demand
      player_pose: player/pose
      robot_pose: motor/joint_state
