/basic_trajectory:
  ros__parameters:
    names:
      left_wheel_motor: left_wheel_motor
      pan_motor: pan_motor
      right_wheel_motor: right_wheel_motor
      tilt_motor: tilt_motor
    predict:
      max_buffer_len: 2
    range_lut:
      step: 1.0 # m between values starting at zero
      values: # range
      - 2.5 # requested velocity at x range
      - 4.5 # 1.0m
      - 6.5 # 2.0m
      - 8.5 # 3.0m
      - 10.5 # 4.0m
      - 12.5 # 5.0m
      - 14.5 # 6.0m
      - 16.5 # 7.0m
      - 18.5 # 8.0m
      - 20.5 # 9.0m
      - 22.5 # 10.0m
      - 24.5 # 11.0m
      - 26.5 # 12.0m
      - 28.5 # 13.0m
      - 30.5 # 14.0m
      - 32.5 # 15.0m
      - 34.5 # 16.0m
      - 36.5 # 17.0m
      - 38.5 # 18.0m
      - 38.5 # 19.0m
      - 38.5 # 20.0m

    vel_lut:
      step: 4.0 # m/s requested between values
      values: # maps m /s to radians at the motor
      - 11.0 # 00 m/s
      - 11.5 # 04 m/s
      - 12.0 # 08 m/s
      - 12.5 # 12 m/s
      - 13.0 # 16 m/s
      - 13.5 # 20 m/s
      - 14.0 # 24 m/s
      - 15.0 # 28 m/s
      - 16.0 # 32 m/s
      - 17.0 # 36 m/s
      - 18.0 # 40 m/s

    solver:
      max_time: 5.0
      min_pose_samples: 1
      run_period: 0.05
      time_step: 0.2
    topic:
      motor_template: motor/{}/demand
      player_pose: player/pose
      robot_pose: motor/joint_state
